[package]
name = "icap-ebpf"
version = "0.1.0"
edition = "2021"

[dependencies]
icap-common = { path = "../icap-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "icap"
path = "src/main.rs"
